server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: employee-services
          uri: lb://employee-services
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
